spring:
  application:
    name: car-service
  boot:
    admin:
      client:
        url: http://localhost:8081/


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always